### ISSUE TITLE
Please add plugins to webjar

### ISSUE THREAD

**Issue by trevershick** [webjars/mousetrap#4]
I use the global-bind plugin.  They're all in the plugins/ subfolder inside mousetrap's repo.
This issue is not very detailed as a PR will accompany it shortly.

The ultimate goal is to get all plugins js files like so:

    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-bind-dictionary.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-bind-dictionary.min.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-global-bind.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-global-bind.min.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-pause.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-pause.min.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-record.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap-record.min.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap.js
    META-INF/resources/webjars/mousetrap/1.5.3/mousetrap.min.js

**Comment by jamesward** [comment]
Fixed via #5
